### PR TITLE
fix two-row feed info issue

### LINKED ISSUE #1471: Deal with two-row feed_info.txt
The current Foothill Transit (ITP ID `112`) feed's `feed_info.txt` has two rows with two sets of active dates (both have the same start date) and the same feed version identifier. 
image

This causes fanout in the warehouse, because we have two copies of the same feed in `gtfs_schedule_dim_feeds`. Specifically, a test is failing on `gtfs_schedule_fact_daily_trips` because we have two copies of the same trip. 

While this is clearly a bug in their feed, I am not entirely sure how to address this in the warehouse. I am inclined to put in a hacky condition in `gtfs_schedule_dim_feeds` or `feed_info_clean` to filter out one of these rows specifically because this should be rare and putting in logic that tries to programmatically address this kind of situation is unlikely to be robust.

AC:
- [ ] Only one row in `gtfs_schedule_dim_feeds` for the Foothill Transit feed from `2022-05-03`. 
- [ ] The unique combination of columns test on `gtfs_schedule_fact_daily_trips` should pass.

### PR DESCRIPTION
**Pull request by lauriemerrell**
# Description

This is a slightly hacky fix for #1471. This has been an issue for a while but now that we have RT data for Foothill Transit (#1794) it is causing the `gtfs_rt_fact_daily_validations_errors` incremental table to fail to build. This is a more significant effect than anything else so far so I think it's worth fixing this ASAP to get that table working. 

Resolves #1471

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] agencies.yml

## How has this been tested?

I ran the updated version in my local dbt to create `cal-itp-data-infra-staging.laurie_views.gtfs_schedule_dim_feeds` and then compared that with the prod table:

```
SELECT  
  t1.feed_key,
  t1.calitp_itp_id,
  t1.calitp_url_number,
  t1.calitp_extracted_at,
  t2.feed_key,
  t2.calitp_itp_id,
  t2.calitp_url_number,
  t2.calitp_extracted_at
FROM `cal-itp-data-infra.views.gtfs_schedule_dim_feeds` AS t1
FULL OUTER JOIN `cal-itp-data-infra-staging.laurie_views.gtfs_schedule_dim_feeds` AS t2
  USING(feed_key)
WHERE t1.feed_key IS NULL or t2.feed_key IS NULL
ORDER BY t1.calitp_extracted_at DESC
```

Confirmed that the only rows affected by this change are the 4 faulty Foothill Transit feeds:
image

### CODE REVIEW

File: warehouse/models/gtfs_views/gtfs_schedule_dim_feeds.sql [hunk 1]
```diff
@@ -5,8 +5,21 @@ WITH calitp_feeds AS (
...
+        *,
+        RANK() OVER (
+            PARTITION BY
+                calitp_itp_id,
+                calitp_url_number,
+                feed_start_date,
+                feed_version,
+                calitp_extracted_at
+            ORDER BY feed_end_date DESC
+        ) AS row_num
```
Comment (atvaccaro) [inline warehouse/models/gtfs_views/gtfs_schedule_dim_feeds.sql:22]: bit confusing that it's `RANK()` and `AS row_num` but idc that much

**Review by atvaccaro — APPROVED** [review]
