### PR TITLE
Fix gtfs rt define schemas for trip updates & service alerts

### LINKED ISSUE #1002: RT Pipeline: Load structured data about realtime data into the warehouse
This issue aims to track progress towards transforming the raw downloaded RT protobuf files into a format that can be used in BigQuery

- [x] #356 
- [x] #840 (closed in favor of #1011)
- [x] #1011 (tracking trip updates and service alerts)
- [x] #1051
- [x] #1104 (added by @lauriemerrell)

### LINKED ISSUE #1104: Define BQ schemas for trip updates and service alerts
Following the success of #1056, we have confirmed that we are going to follow that same approach to define explicit schemas for all the RT external tables in BigQuery. 

We need to define schemas for:

- [ ] Trip updates
- [ ] Service alerts

### PR DESCRIPTION
**Pull request by lauriemerrell**
# Overall Description

Resolves #1104 (and therefore resolves #1002) by defining schemas for trip updates and service alerts data. 

## Checklist for all PRs

- [x] Run `pre-commit run --all-files` to make sure markdown/lint passes
- [x] Link this pull request to all issues that it will close using keywords (see GitHub docs about [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). Also mention any issues that are partially addressed or are related.

## Airflow DAG changes checklist

- [x] Include this section whenever any change to a DAG in the `airflow/dags` folder occurs, otherwise please omit this section.
- [x] Verify that all affected DAG tasks were able to run in a local environment
- [x] Take a screenshot of the graph view of the affected DAG in the local environment showing that all affected DAG tasks completed successfully
image
- [x] Add/update documentation in the `docs/airflow` folder as needed
- [x] Fill out the following section describing what DAG tasks were added/updated

This PR updates the `rt_loader` DAG in order to update the following DAG tasks:

- `external_trip_updates`: define schema 
- `external_service_alerts`: define schema

### CODE REVIEW

File: airflow/dags/rt_loader/external_trip_updates.sql [hunk 1]
```diff
@@ -5,7 +5,50 @@ dependencies:
...
+        uncertainty INT64
+        >,
+      departure STRUCT <
+        delay INT64,
+        time INT64,
+        uncertainty INT64
+        >,
+      scheduleRelationship STRING
+      >
+      >,
```
Comment (evansiroky) [inline airflow/dags/rt_loader/external_trip_updates.sql:47]: nit: can you fix the indentation here?

Comment (evansiroky) [inline airflow/dags/rt_loader/external_trip_updates.sql:47]: nit: can you fix the indentation? Maybe something like this?

```suggestion
    stopTimeUpdate ARRAY<
      STRUCT<
        stopSequence INT64,
        stopId STRING,
        arrival STRUCT <
          delay INT64,
          time INT64,
          uncertainty INT64
          >,
        departure STRUCT <
          delay INT64,
          time INT64,
          uncertainty INT64
          >,
        scheduleRelationship STRING
      >
    >,
```

**Review by evansiroky — APPROVED** [review]
Good to go after fixing the one indentation issue.

**Review by atvaccaro — APPROVED** [review]
thank you!
