### PR TITLE
fix(payments): Correct cardinality for micropayments:transactions

### LINKED ISSUE #1068: Bug: Payments pipeline blocked due to invalid transaction assumptions
**Describe the bug**
We're currently enforcing that a transaction (essentially a tap) is only associated with one micropayment (essentially, we thought, a trip). However, as can be seen below, transactions can be associated with multiple micropayments. As a result, our pipeline cannot proceed. If we allow it to, it will result in fan-out in the final `payments_rides` table.

image

image

Currently (as of 2022 Feb 11) there is only one transaction that is breaking, so the impact of any resulting fan-out would be very small.

I think what should happen is that we:
* Relax the invariant that a device transaction can only be associated with one micropayment by removing [the uniqueness constraint on `littlepay_transaction_id`](https://github.com/cal-itp/data-infra/blob/2ee7ed8d92ae9bc26b495812e260bac601230f25/airflow/dags/payments_views_staging/stg_cleaned_micropayment_device_transactions.sql#L12-L13) and removing [the micropayment device transaction validation table](https://github.com/cal-itp/data-infra/blob/2ee7ed8d92ae9bc26b495812e260bac601230f25/airflow/dags/payments_views_staging/validate_cleaned_micropayment_device_transactions.sql)
* Remove the expectation that each `payment_rides` record only corresponds to one micropayment.
  1. In the near term, we can just use the earliest `micropayment_id` associated with the transactions
  2. In the longer term, perhaps we should remove `micropayment_id`, `adjustment_id`, and `product_id` from the rides table since these potentially become 1:many relationships. This may be the necessary impetus to switch to a more star-like schema and rethink the rides table (though it is very nice to allow agencies to download a nice wide flat version of their ride data).
* To calculate ride charges, either:
  * Sum the `charge_amount` across all micropayments associated with device transactions to arrive at the final cost of a ride (this will result in some rides with `charge_amount` values differing from the `nominal_amount` values with no immediately apparent adjustments)
  * Or, have a `debited_amount` column, a `credited_amount` column, and a `final_amount` column that is the sum of the two.

**To Reproduce**
1.  Run the following in BQ to get all transactions associated with multiple micropayments:
    ```sql
    with

    multplied_transaction_ids as (
        select littlepay_transaction_id
        from `payments.stg_cleaned_micropayment_device_transactions`
        group by 1
        having count(*) > 1
    )

    select littlepay_transaction_id, m.*
    from `payments.stg_cleaned_micropayment_device_transactions`
    join `payments.stg_cleaned_micropayments` m using (micropayment_id)
    join multplied_transaction_ids using (littlepay_transaction_id)
    order by transaction_time desc, littlepay_transaction_id, charge_type desc
    ```
    One of those will be `0d4aae68-e4ea-4319-8fd1-6932184596e9`.
2.  Run the following to get the micropayments associated with the above transaction:
    ```sql
    select *
    from payments.stg_cleaned_micropayment_device_transactions
    join payments.stg_cleaned_micropayments using (micropayment_id)
    where littlepay_transaction_id = '0d4aae68-e4ea-4319-8fd1-6932184596e9'
    ```
    This should result in two micropayments, one with `type=DEBIT` and `charge_type=flat_fare` and `charge_amount=1.75`, and the other with `type=CREDIT` and `charge_type=refund` and `charge_amount=-1.75`.

**Expected behavior**
The `rides` table still has a single record for each complete trip, and takes all the credits, debits, and adjustments into account.

### PR DESCRIPTION
**Pull request by mjumbewu**
# Overall Description

We're currently enforcing that a transaction (essentially a tap) is only associated with one micropayment (essentially, we thought, a trip). However, transactions _can_ be associated with multiple micropayments. Normally we would expect only 1 micropayment per transaction except in the case of refunds, where we will see an additional micropayment with `type='CREDIT'`. This PR takes the distinction between DEBIT and CREDIT micropayments into account.

Resolves #1068

## Airflow DAG Updates

This PR updates tasks across the `payments_views_staging` and `payments_views` DAGs.

* `payments_views`
  * `payments_rides`
    * Only count DEBIT micropayments as rides
    * Add a `refund_amount` column to account for refunds
  * `sbmtd_transactions`
    * Only count DEBIT micropayments
* `payments_views_staging`
  * `stg_cleaned_micropayment_device_transactions`
    * Remove the unique `littlepay_transaction_id` check
    * Update descriptions and comments
  * `validate_cleaned_micropayment_device_transactions`
    * Check that `littlepay_transaction_id` values are unique only when joined with DEBIT micropayments

## Successful Run Screenshots

Screenshot-2022-02-23-17:12:17

Screenshot-2022-02-23-17:13:33

### CODE REVIEW

**Review by evansiroky — CHANGES_REQUESTED** [review]
Can you please post a screenshot of the affected DAG tasks passing on a local airflow instance?

**Comment by mjumbewu** [comment]
@evansiroky added screenshots to the PR description

**Review by evansiroky — APPROVED** [review]

File: airflow/dags/payments_views/payments_rides.sql [hunk 1]
```diff
@@ -153,7 +172,8 @@ SELECT
     t2.latitude AS off_latitude,
     t2.longitude AS off_longitude
 
-FROM `payments.stg_cleaned_micropayments` AS m
+FROM debited_micropayments AS m
+LEFT JOIN refunded_micropayments AS mr USING (micropayment_id)
 JOIN `payments.stg_cleaned_customers` AS c USING (customer_id)
 LEFT JOIN `payments.stg_cleaned_customer_funding_source_vaults` AS v
```
Comment (atvaccaro) [inline airflow/dags/payments_views/payments_rides.sql:178]: nit: is this intended to be an inner join? if so, could it be made explicit?

**Review by atvaccaro — APPROVED** [review]
lgtm!

File: airflow/dags/payments_views/payments_rides.sql (hunk 1 above)
Comment (evansiroky) [reply airflow/dags/payments_views/payments_rides.sql:178]: I wanted to make sure these payment fixes got in tonight so I created https://github.com/cal-itp/data-infra/issues/1120 in case we want to work on this later.
